#!/bin/bash

cat > /tmp/tmp$$.c << EOF
#include <stdio.h>
#include <stdlib.h>

int main(void) {
$@
return 0;
}
EOF

gcc -std=c99 -pipe -O2 -Wall /tmp/tmp$$.c -o /tmp/tmp$$ && /tmp/tmp$$ && rm /tmp/tmp$$
rm /tmp/tmp$$.c

