#!/bin/sh

CC="gcc -std=c99"
CFLAGS="-O2 -pipe -Wall -Wextra -pedantic"
src=/tmp/tmp$$.c
out=/tmp/tmp$$

trap 'rm -f "$out" "$src"' EXIT

cat > "$src" <<HEREDOCTHEREDOCEVERYWHEREADOCDOC
#define _GNU_SOURCE
#include <errno.h>
#include <fcntl.h>
#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <sys/stat.h>
#include <unistd.h>

int main(void) {
  $@
  return 0;
}
HEREDOCTHEREDOCEVERYWHEREADOCDOC

$CC $CFLAGS $src -o "$out" && "$out"

