#!/bin/bash

NUMFIELDS=0
OUT=()

# use a common FD based on where we read from
case $# in
  0) exec 6<&0 ;;
  *) exec 6< "$1" ;;
esac

trap 'exec 6<&-' 0

OUT+=("<table>")
while IFS=',' read -r -a items; do
  OUT+=("\t<tr>") # start row

  (( ${#items[@]} == 0 )) && continue

  # assert: all rows are same number of columns
  (( NUMFIELDS == 0 )) && NUMFIELDS=${#items[@]}
  if (( NUMFIELDS != ${#items[@]} )); then
    echo "error: Malformed CSV. Expected $NUMFIELDS fields, found ${#items[@]}" >&2
    exit 1
  fi

  for item in "${items[@]}"; do
    OUT+=("\t\t<td>$item</td>") # column
  done

  OUT+=("\t</tr>") # end row
done <&6
OUT+=("</table>")

for line in "${OUT[@]}"; do
  echo -e $line
done

