#!/bin/bash

dropbox=~/tmp

inotifywait -qm --event CREATE --format %f $dropbox | while read $file; do
	case "${file##*.}" in
	   "flac")	mv "$dropbox/$file" /path/to/flac ;;
	   "mp3")	mv "$dropbox/$file" /path/to/lame ;;
	   "mkv")	mv "$dropbox/$file" /path/to/vid ;;
	esac
done
