#!/bin/bash
#
# resolve ELF library deps to pacman packages
#

declare -r lddregex=$'(.+) => (.+) \(0x[a-fA-F0-9]+\)'

resolve_bin() {
  declare -A depmap
  declare -a linkage

  local lddout=$(ldd "$1" 2>/dev/null) || return

  # leverage the linker to do lib resolution
  while read -r line; do
    [[ $line =~ $lddregex ]] || continue
    depmap["${BASH_REMATCH[1]}"]=${BASH_REMATCH[2]}
  done <<< "$lddout"

  pacman -Ql | grep -Ff \
    <(objdump -p "$1" | while read section soname; do
        [[ $section == NEEDED && ${depmap[$soname]} ]] && printf '%s\n' "${depmap[$soname]}"
      done) | cut '-d ' -f1 | sort -u
}

for bin; do
  resolve_bin "$bin"
done | sort -u
