#!/bin/bash

if [[ $# -lt 2 ]]; then
    echo "Usage: $0 <device> <ip_address> [gateway]"
    exit 1
fi

iface=$1
ip=$2
netmask="255.255.255.0"
broadcast=$(echo $2 | cut -d. -f1-3).255

if [[ -z $3 ]]; then
    gateway=$(echo $2 | cut -d. -f1-3).1
else
    gateway=$3
fi

sudo ifconfig $iface $ip netmask $netmask broadcast $broadcast
sudo route add default gw $gateway $iface
sudo ifconfig $iface up
