#!/bin/bash

echo "Network Device Statistics (in mb)"
printf "\n%8s%10s%10s%8s\n" "Device" "Sent" "Received" "Ratio"
#echo ---------------------------------------
for dev in /sys/class/net/*; do
    dev=${dev##*/}
    stats=($(awk "/[\ ]*$dev:/"'{print $2,$10}' /proc/net/dev))
    sent=$(posty <<< ":2 ${stats[1]} 1024 / 1024 /")
    recv=$(posty <<< ":2 ${stats[0]} 1024 / 1024 /")
    ratio=$(posty <<< ":2 $sent $recv /")
    printf "%8s%10.2f%10.2f%8.2f\n" $dev $sent $recv $ratio
done
echo 
