#!/bin/bash

[[ -z $1 ]] || [[ ! -h /sys/class/net/$1 ]] && echo "Provide a network interface" && exit 1

stats=($(cat /proc/net/dev | grep $1 | cut -d: -f2 | awk '{print $1 " " $9}'))
# [0] = received
# [1] = sent

echo Stats for: $1
printf "Received: %5.2fmb\n" $(echo "scale=2;${stats[0]} / 1024 / 1024" | bc -l)
printf "    Sent: %5.2fmb\n" $(echo "scale=2;${stats[1]} / 1024 / 1024" | bc -l)
