#!/bin/bash

shopt -s extglob

fakedb=/dev/shm/fakepacdb
realdb=/var/lib/pacman

[[ ! -d $fakedb ]] && { mkdir -p "$fakedb/sync" || exit 1; }
[[ ! -L $fakedb/local ]] && { ln -s "$realdb/local" "$fakedb" || exit 2; }

case $1 in
  -Sy|-Syy) exec fakeroot pacman --dbpath "$fakedb" $1 ;;
  -@(S|U)*) echo "action not allowed" ;;
  *) exec pacman --dbpath "$fakedb" $1 ;;
esac

