#!/bin/bash

PACDB="/var/lib/pacman/local"

[[ -z $1 ]] && "Need a valid package to query" && exit 1

multifound() {
	echo -e "${#pkgs[*]} packages found:\n"
	for pkg in ${pkgs[*]}; do
		printf "  %s\n" $pkg
	done
	echo -e "\nPlease refine your search."
	exit 0
}

listfiles() {
	sed -n -e '/%FILES%/,/^$/p' $PACDB/$1-*/files | less
	exit 0
}

pkgs=($(pacman -Qs $1 | grep -e ^local | cut -d\/ -f2 | cut -d\  -f1))

[[ $pkgs = $1 ]] && listfiles $1

case ${#pkgs[*]} in
	0) echo "No package '$1' found" ;;
	1) listfiles $1 ;;
	*) multifound ;;
esac

