#!/bin/bash

for package in $(pacman -Qqm); do
  pkg=($(awk -F':' '/^Version/{print $2} /^Provides/{ gsub(/^[ \t]+/, "", $2); print $2 };' <(pacman -Qi $package)))

  for p in ${pkg[@]:1}; do
    [[ $p == "None" ]] && continue

    pacver=($(awk -F':' '/^Version/{ gsub(/^[ \t]+/, "", $2); print $2 }' <(pacman -Si ${p%=*} 2>/dev/null)))
    [[ -z ${pacver[0]} ]] && continue

    # If they only differ in the build version, skip it
    [[ ${pacver[0]%-*} == ${pkg[0]%-*} ]] && continue

    if [[ $(vercmp ${pacver[0]} ${pkg[0]}) -gt 0 ]]; then
      echo -e "${p%=*} \033[1;31m${pkg[0]}\033[1;0m -> \033[1;32m${pacver[0]}\033[1;0m"
    fi
  done
done

