#!/bin/bash

[[ $1 = "-h" ]] && {
  echo "Usage: ${0##*/} [-f] [command]";
  echo;
  echo "     -f      suppress prompting before a custom command is run";
  echo;
  echo "repos with uncommitted changes will be reported if no command is provided";
  exit 1;
}

repohome=$HOME
fail=0
success=0

msg() {
  local mesg=$1; shift
  printf "\033[1;32m==>\033[1;0m\033[1;1m ${mesg}\033[1;0m\n" "$@" >&2
}

if [[ $# -gt 0 ]]; then
  if [[ $1 = "-f" ]]; then
    shift
  else
    msg "Command to be executed: $*"
    read -N1 -p "  Are you sure you want to do this? [y/N] " reply
    echo

    [[ ! "$reply" =~ [Yy] ]] && exit 1
  fi
fi

while read repo; do
  repo=${repo%.git}
  cd "$repo"
  if [[ $# -eq 0 ]]; then
    [[ $(git status -s | grep -v "^??" | wc -l) -gt 0 ]] && echo "$repo"
  else
    msg "In '$repo'";
    "$@" && (( success++ )) || (( fail++ ))
    echo;
  fi
done < <(find "$repohome" -type d -name '.git')

if [[ $# -ne 0 ]]; then
  echo "Job summary for: $@"
  echo "Successes : $success"
  echo "Errors    : $fail"
fi
