#!/bin/bash
#
# show code ownership of a git repo by lines of code
#
# modified from original, found at:
# http://stackoverflow.com/questions/4589731/git-blame-statistics
#

git ls-tree --name-only -r HEAD |
  file -f - |
  sed '/: .*text/s/: .*//' |
  while read filename; do git blame -M -C "$filename"; done |
  sed -r 's/.*\((.*)[0-9]{4}-[0-9]{2}-[0-9]{2} .*/\1/;s/ +$//' |
  sort |
  uniq -c |
  sort -n

