#!/bin/bash
#
# Emulates hg's `outgoing' command
#

ORIGIN=${1:-origin}

# get remote HEAD (assumes origin as remote)
read remote_head _ < <(git ls-remote $ORIGIN HEAD 2>/dev/null)
[[ -z $remote_head ]] && exit 1

# find remote_head in local commits
n=$(sed -n "/$remote_head/=" <(git rev-list --all))

if [[ ! $n ]]; then
  echo "remote > local"
elif (( n == 1 )); then
  echo "nothing to commit"
else
  (( n-- ))
  echo "Outstanding commits:"
  git --no-pager log --pretty=oneline HEAD~$n..

fi

