#!/bin/bash
#
# show code ownership of a git repo by lines of code
#
# modified from original, found at:
# http://stackoverflow.com/questions/4589731/git-blame-statistics
#

IFS=$'\n' read -r -d '' -a all < \
  <(git ls-files | file -f - | sed '/: .*text/s/: .*//')

for file in "${@:-${all[@]}}"; do git blame -M -C "$file"; done |
  sed -r 's/.*\((.*)[0-9]{4}-[0-9]{2}-[0-9]{2} .*/\1/;s/ +$//' |
  sort |
  uniq -c |
  sort -n

