#!/bin/bash

#
# http://man.cx manpage extractor
# requires: xmllint (libxml2)
#

BASEURL='http://man.cx'
XMLLINT='xmllint --html'
XPATH_EXPR='//*[@id="manpage"]/*[self::pre or self::h3]'
DETAG='$d;s|</\?[^>]\+>||g;s|&lt\;|<|g;s|&gt\;|>|g'

usage() {
  echo "Usage: ${0##*/} [section] manpage" >&2
}

# less gets color, else its a NOOP
if [[ ${PAGER:-less} = less ]]; then
  colorify() {
    sed '/^[[:upper:][:blank:]]\+$/{
      s/^/'"$LESS_TERMCAP_md"'/
      s/$/'"$LESS_TERMCAP_ue"'/
    }'
  }
else
  colorify() { cat; }
fi

case $# in
  1) PAGE=$1 ;;
  2) SECTION="($1)"
     PAGE=$2 ;;
  *) usage; exit 1 ;;
esac

# if found locally, exit
man ${SECTION//[^[:digit:]]/} $PAGE 2>/dev/null && exit

manpage=$(curl -s $BASEURL/$PAGE$SECTION | $XMLLINT --xpath "$XPATH_EXPR" - 2>/dev/null | sed "$DETAG" | colorify)
[[ $manpage ]] && "${PAGER:-less}" <<< "$manpage" || echo "No mancx entry for $PAGE"
