#!/bin/bash

#
# http://man.cx manpage extractor
# requires: xmllint (libxml2)
#

BASEURL='http://man.cx'
XMLLINT='xmllint --html'
XPATH_EXPR='//*[@id="manpage"]/pre | //*[@id="manpage"]/h3'
DETAG='$d;s|</\?[^>]\+>||g;s|&lt\;|<|g;s|&gt\;|>|g'

usage() {
  echo "Usage: ${0##*/} [section] manpage" >&2
}

case $# in
  1) PAGE=$1 ;;
  2) SECTION="($1)"
     PAGE=$2 ;;
  *) usage; exit 1 ;;
esac

man $SECITON $PAGE 2>/dev/null
(( $? == 0 )) && exit 0

manpage=$(curl -s $BASEURL/$PAGE$SECTION | $XMLLINT --xpath "$XPATH_EXPR" - 2>/dev/null | sed "$DETAG")
[[ $manpage ]] && "${PAGER:-less}" <<< "$manpage" || echo "No mancx entry for $PAGE"
