#!/bin/bash

declare curpkg= pkg= file=
declare -i tolerance=$1 filecount= hitcount=

summary() {
  local ratio=

  # boring
  if (( hitcount == filecount )); then
    return
  fi

  # under tolerance
  ratio=$(( hitcount * 100 / filecount % 100 ))
  if (( ratio < tolerance )); then
    printf '%-30s %-10s (%s%%)\n' "$pkg" "$hitcount/$filecount" "$ratio"
  fi
}

pacman -Ql | while read pkg file; do
  if [[ -z $curpkg || $pkg != "$curpkg" ]]; then
    summary "$pkg" "$hitcount" "$filecount"
    curpkg=$pkg
    hitcount=0
    filecount=0
  fi

  # skip directories
  [[ $file = */ ]] && continue;

  (( ++filecount ))
  [[ -e "$file" || -L "$file" ]] && (( ++hitcount ))
done
