#!/bin/bash
#
# pacfilecheck: compares files that pacman tracks to what's actually
#   on the filesystem
#

declare curpkg= pkg= file=
declare -i tolerance=${1:-100} filecount= hitcount=

summary() {
  local ratio=

  # boring
  if (( hitcount == filecount )); then
    return
  fi

  # under tolerance
  ratio=$(( hitcount * 100 / filecount % 100 ))
  if (( ratio < tolerance )); then
    printf '%-30s %-10s (%s%%)\n' "$pkg" "$hitcount/$filecount" "$ratio"
  fi
}

usage() {
  printf 'usage: %s [tolerance]\n' "${0##*/}"
  printf '       tolerance defaults to 100 if unspecified\n'
  exit 1
}

if [[ $1 = -h || ( $1 && $1 != +([[:digit:]]) ) ]]; then
  usage
fi

pacman -Ql | while read pkg file; do
  if [[ -z $curpkg || $pkg != "$curpkg" ]]; then
    summary "$pkg" "$hitcount" "$filecount"
    curpkg=$pkg
    hitcount=0
    filecount=0
  fi

  # skip directories
  [[ $file = */ ]] && continue;

  (( ++filecount ))
  [[ -e "$file" || -L "$file" ]] && (( ++hitcount ))
done
