#!/bin/bash
# list directory permissions along the path

IFS='/' read -r -a dirpath <<< "${1:-$(pwd)}"

for part in "${dirpath[@]}"; do
  working+="$part/"
  find "$working" -maxdepth 0 -printf "%M %10u %10g %p\n"
done
