#!/bin/bash
# list directory permissions along the path

IFS='/' read -r -a dirpath <<< "${1:-$(pwd)}"

for part in "${dirpath[@]}"; do
  working+="$part/"
  stat $working --printf "%A %U %G %n\n"
done | column -t
