#!/bin/bash
#
# launcher script for qemu-kvm
#
# machines are sourced from a file which defines functions, each
# specifying options for the particular VM, for example:
#
# vm_beatbox() {
#   cdrom="-cdrom $isoroot/archlinux-2011.05.08-core-x86_64.iso -boot d"
#
#   opts=(-nographic)
#   drives=(
#     "-drive file=$imgroot/beatbox.1.qcow2,if=virtio"
#     "-drive file=$imgroot/beatbox.2.qcow2,if=virtio"
#   )
# }
#

### Paths ################################
declare -r machines=$XDG_CONFIG_HOME/qemu/machines
declare isoroot=/mnt/Gluttony/iso
declare imgroot=/mnt/Haven/qemu-img

### Defaults #############################
declare mem="-m 1024"
declare cpus="-smp 4"
declare net="-net vde -net nic,model=virtio"

### Launcher #############################

. "$machines"

while getopts 'c' flag; do
  case $flag in
    c) usecdrom=true ;;
  esac
done
shift $(( OPTIND - 1 ))

if [[ -z $1 ]]; then
  printf 'Available VMs:\n'
  compgen -A function -- vm_ | sed 's/^vm_/   /'
  exit 0
fi

if ! type -t vm_$1 >/dev/null; then
  printf 'unknown VM: %s\n' "$1"
  exit 1
fi

vm_$1; shift

exec qemu-kvm "${opts[@]}" $cpus $mem ${drives[@]} $net ${usecdrom:+$cdrom} "$@"

