#!/bin/bash

#
# fetch the latest PKGBUILD from Arch's SVN
# optdep: expac
#

shopt -s extglob

svnrepo="svn://svn.archlinux.org"

getrepo() {
  if type -P expac &>/dev/null; then
    expac -S '%r' $1
  else
    LC_ALL=C pacman -Si $1 2>/dev/null | sed -n '/^Repo/{s/.*: \(.*\)/\1/p;q}'
  fi
}

[[ -z $1 ]] && { printf "Usage: %s targets...\n" "${0##*/}"; exit 1; }

for pkg; do
  # read only the first, repo is only of mild importance
  read repo _ < <(getrepo $pkg)
  [[ -z $repo ]] && { printf "error: package \`%s' not found" "$pkg"; continue; }

  case $repo in
    @(community|multilib)*) repo=community ;;
    *) repo=packages ;;
  esac

  [[ -d $pkg ]] && { printf "error: directory \`%s' already exists" "$pkg"; continue; }

  svn export "$svnrepo/$repo/$pkg/trunk" $pkg >/dev/null &&
    printf ":: checked out %s\n" "$pkg" ||
    printf "error: failed to get package \`%s'\n" "$pkg"

done

