#!/bin/bash

if [[ $UID -eq 0 ]]; then
    echo "Setting hwclock to localtime from time.nist.gov..."
    hwclock --set --date="$(cat < /dev/tcp/time.nist.gov/13 | awk '{print $2,$3}') UTC"
    echo "Sync'ing hwclock to system..."
    hwclock -s
else
    echo "Must be root to execute this!" >&2
fi
