#!/bin/bash

# dump our dbus address to a file
if [[ -z $DBUS_SESSION_BUS_ADDRESS ]]; then
  # fffff, go find it
  read machine_id < /etc/machine-id
  if [[ $machine_id && -f ~/.dbus/session-bus/$machine_id-${DISPLAY#:} ]]; then
    . ~/.dbus/session-bus/$machine_id-${DISPLAY#:}
    unset machine_id
  fi
fi
echo "$DBUS_SESSION_BUS_ADDRESS" > ~/.dbus_address

# start terminals here so that they're explicitly started
# _after_ the consolekit session is created.
urxvtd -q -o -f
urxvtc -name tmux -geometry 122x77 -e tmux -L main attach
urxvtc -name htop -e htop
urxvtc -name ncmpcpp -e ncmpcpp
urxvtc -name werk

chromium &

cconfig="${XDG_CONFIG_HOME:-$HOME/.config}/conky/conkyrc"
conky -c "$cconfig" | while read out; do
  xsetroot -name "$out"
done &

while true; do
  dwm 2> ~/.dwm.log
done

