#!/bin/bash


cconfig="${XDG_CONFIG_HOME:-$HOME/.config}/conky/conkyrc"
conky -c "$cconfig" | while read out; do
  xsetroot -name "$out"
done &

# start terminals here so that they're explicitly started
# _after_ the consolekit session is created.
urxvtd -q -o -f
urxvtc -name tmux -geometry 122x77 -e tmux -L main attach
urxvtc -name htop -e htop
urxvtc -name ncmpcpp -e ncmpcpp
urxvtc -name werk

while true; do
  dwm 2> ~/.dwm.log
done

