#!/bin/bash

usage="usage: ${0##*/} -c <+|-> <-i increment> <-m mixer>"
command=
increment=5%
mixer=PCM

while getopts i:h o; do
  case "$o" in
    i) increment=$OPTARG;;
    h) echo "$usage"; exit 0;;
    ?) echo "$usage"; exit 0;;
  esac
done

shift $(($OPTIND - 1))
command=$1

if [[ ! $command =~ [+-] ]]; then
    echo $usage
    exit 0;
fi

display_volume=$(amixer set $mixer $increment$command unmute | awk '/^[\ ]*Front Left/{print $4}')

icon_name="notification-audio-volume-"

if [[ $display_volume -gt 67 ]]; then
  icon_name+="high"
elif [[ $display_volume -gt 33 ]]; then 
  icon_name+="medium"
elif [[ $display_volume -gt 0 ]]; then 
  icon_name+="low"
else
  icon_name+="muted"
fi

notify-send " " -i $icon_name -h int:value:$display_volume -h string:synchronous:volume -t 1000
