#!/bin/bash
#
# This is intended to be a hook from a WM to notify-osd. There's not much sense
# in calling this directly.
#
# Requires: ossmix for OSS, amixer for ALSA
#
# Example dwm usage:
# static const char *volup[]     = { "volOSD", "oss", "pcm2", "+5",     NULL };
# static const char *voldown[]   = { "volOSD", "oss", "pcm2", "-5",     NULL }; 
# static const char *voltoggle[] = { "volOSD", "oss", "pcm2", "toggle", NULL };
#

# this should be 'alsa' or 'oss'
output=$1

# mixer name (e.g. PCM or pcm2)
mixer=$2

# amount to adjust mixer level by (-10, -5, 10)
increment=$3

# temp file for storing volume when muting
volstore=~/.volume

get_icon () {
  icon_name="notification-audio-volume-"

  if [[ $display_volume -gt 67 ]]; then
    icon_name+="high"
  elif [[ $display_volume -gt 33 ]]; then 
    icon_name+="medium"
  elif [[ $display_volume -gt 0 ]]; then 
    icon_name+="low"
  else
    icon_name+="muted"
  fi

  echo $icon_name
}

oss_adjust () {
  local inc=$2
  if [[ -f "$volstore" && $increment -gt 0 ]]; then
    inc=$(( $(< "$volstore") + $increment ))
    rm "$volstore"
  fi

  display_volume=$(sed -n 's|.*:\([0-9\.]*\)$|\1|p' <(ossmix $mixer -- $inc))
  display_volume=${display_volume%.*} # truncate decimal if any
}

oss_toggle () {
  if [[ -f "$volstore" ]]; then
    increment=$(< "$volstore")
    rm -f "$volstore"
  else
    ossmix $1 | sed -n 's|.*:\([0-9]*\)|\1|p' > "$volstore"
    increment=0
  fi
}

alsa_adjust () {
  local cur_vol=$(amixer sget $mixer | awk '/^  Front/{ print $4; exit }')
  display_volume=$(( $cur_vol + $increment ))

  amixer sset $mixer $display_volume >/dev/null
}

alsa_toggle () {
  if [[ -f "$volstore" ]]; then
    increment=$(< "$volstore")
    rm -f "$volstore"
  else
    amixer sget $mixer | awk '/^  Front/{ print $4; exit }' > "$volstore"
    increment=-$(< "$volstore")
  fi
}

[[ $3 == "toggle" ]] && ${output}_toggle $mixer
${output}_adjust $mixer $increment

echo $display_volume

notify-send " " -i $(get_icon) -h int:value:$display_volume -h string:synchronous:volume -t 1000
