#!/bin/bash

IFS=$'\n' read -r -d $'\0' -a waffles < <(find /mnt/Gluttony/waffles -type f -links 1 -iname \*.flac -exec dirname {} \; | sort -u)

[[ $# -eq 1 ]] && set $1 1
[[ $# -eq 2 ]] && {
    for waffle in "${waffles[@]:$1:$2}"; do
        echo $waffle;
    done;
    exit 0;
}

for waffle in "${waffles[@]}"; do echo $waffle; done
