#!/bin/bash

WAFFLE_DIR="/mnt/Gluttony/waffles"

declare -a waffles
while read -d $'\0' waffle; do
  waffles+=("$waffle")
done < <(find "$WAFFLE_DIR" -links 1 -iregex '.*\.\(flac\|mp3\)' -printf '%h\0' | uniq -z)

if [[ -n $1 ]]; then
  items=("${waffles[@]:$1:${2:-1}}")
else
  items=("${waffles[@]}")
fi

(( ${#items[@]} )) && printf "%q\n" "${items[@]}"

