#!/bin/bash

# indent size
IND_SZ=3

get_pwd_contents() {
  local dir nondir

  for f in *; do
    [[ -d $f ]] && dir+=("$f") || nondir+=("$f")
  done

  echo "${dir[@]}" "${nondir[@]}"
}

walk() {
  printf "%*s\e[0;34m%s\e[0m\n" "$indent" "" "$1"

  (( indent += $IND_SZ ))
  pushd "$1" &>/dev/null

  for entry in $(get_pwd_contents); do
    [[ -d $entry ]] && walk "$entry" || printf "%*s%s\n" "$indent" "" "$entry"
  done

  (( indent -= IND_SZ ))
  popd &>/dev/null
}

basedir=${1:-.}

cd "$basedir" 2>/dev/null || { echo "Directory not found: '$basedir'" >&2; exit 1; }

indent=0
walk "$basedir"
