#!/bin/bash

#
# emulates the 'tree' utility
#

shopt -s nullglob

# indent size
IND_SZ=3
DIRS_FIRST=

printentry() {
  printf "%*s%s\n" "$indent" "" "$1"
}

get_pwd_contents() {
  local dir nondir

  for f in *; do
    [[ -d $f ]] && dir+=("$f") || nondir+=("$f")
  done

  echo "${dir[@]}" "${nondir[@]}"
}

walk() {
  local dir_contents
  printentry "$(printf "\e[0;34m%s\e[0m" "$1")"

  (( indent += $IND_SZ ))
  pushd "$1" &>/dev/null

  [[ $DIRS_FIRST ]] && dir_contents=$(get_pwd_contents) || dir_contents=(*)
  for entry in $(get_pwd_contents); do
    [[ -d $entry && ! -L $entry ]] && walk "$entry" || printentry "$entry"
  done

  (( indent -= IND_SZ ))
  popd &>/dev/null
}

while getopts "d" opt; do
  case $opt in
    d) DIRS_FIRST=1 ;;
  esac
done
shift $(( OPTIND - 1 ))

indent=0
(( $# == 0 )) && DIRS=(.) || DIRS=($@)

for basedir in "${DIRS[@]}"; do
  cd "$basedir" 2>/dev/null || { echo "Directory not found: '$basedir'" >&2; continue; }
  walk "$basedir"
done

