#!/bin/bash
#
# A command line utility that mimics xdg-open
# Requires Bash 4.0+
#

# Arg check
[[ $# -ne 1 ]] && { echo "Usage: ${0##*/} <file>" >&2; exit 1; }

# Define handlers per file extension in associative array
declare -A handler

doc=soffice
handler[doc]=$doc
handler[xls]=$doc
handler[odb]=$doc
handler[ods]=$doc
handler[odt]=$doc

image=feh
handler[gif]=$image
handler[jpeg]=$image
handler[jpg]=$image
handler[png]=$image

handler[pdf]=apvlv

video=mplayer
handler[mkv]=$video
handler[mpg]=$video
handler[wmv]=$video
handler[avi]=$video

# Fallback handler (should be a text editor)
default=vim

# Hack off extension
ext=${1//*.}

# Check for non-zero length of $ext and that we found a valid handler
if [[ -z $ext || -z ${handler[$ext]} ]]; then
    $default $1
else
    ${handler[$ext]} "$*"
fi

